config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts do
  	resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	validates :image, presence: true
	validates :user_id, presence: true
	validates :caption, length: { :minimum => 3, :maximum => 300 }

	has_attached_file :image, styles: { :medium => '640x' }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	belongs_to :user
	has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord

	validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_post

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			respond_to do |format|
				format.html {redirect_to :back}
				format.js
			end
		else
			flash[:alert] = "Check the comment form, something went wrong."
			redirect_to root_path
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id])

		@comment.destroy
		
		respond_to do |format|
			format.html {redirect_to root_path}
			format.js
		end
		
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_post
		@post = Post.find(params[:post_id])
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :owned_post, only: [:edit, :update, :destroy]


	def index
		@posts = Post.all
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		 

		if @post.save
			Cloudinary::Uploader.upload(post_params[:image], :public_id => "post_#{@post.id}_image", :crop => :limit, :width => 2000, :height => 2000,)
			flash[:success] = "Your post has been created!"
			redirect_to posts_path
		else
			flash.now[:alert] = "Your post couldn't be created! Please check the form"
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post updated."
			redirect_to posts_path
		else
			flash.now[:alert] = "Update failed. Please check the form"
			render :edit
		end
	end

	def destroy
		if @post.destroy
			flash[:notice] = "Your post was deleted."
			redirect_to posts_path
		else
			flash.now[:error] = "Post failed to be removed. Please try again."
			render :edit
		end
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:image, :caption)
	end

	def owned_post
		unless current_user.id == @post.user.id
			flash[:alert] = "That post does not belong to you!"
			redirect_to root_path
		end
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def alert_for(flash_type)
		{
			success: 'alert-success',
			error: 'alert-danger',
			alert: 'alert-warning',
			notice: 'alert-info'
		}[flash_type.to_sym] || flash_type.to_sym
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
	<div class="user-name">
		<%= comment.user.user_name %>
	</div>
	<div class="comment-content">
		<%= comment.content %>
	</div>
	<% if comment.user == current_user %>
		<%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
			<span class="glyphicon glyphicon-remove delete-comment"></span>
		<% end %>
	<% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%= j render 'comments/comment', post: @post , comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('');

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post , comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('');

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  	<div class="container-fluid navbar-container">
  		<div class="navbar-header">
  			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
  			<span class="sr-only">Toggle Navigation</span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
        <span class="icon-bar"></span>
  			</button>
  			<%= link_to "Photogram", root_path, :class => "navbar-brand" %>
  		</div>
  		<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
  			<ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
  	  			<li><%= link_to "New Post", new_post_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
  	  			<li><%= link_to "Login", new_user_session_path %></li>
  	  			<li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>
  			</ul>
  		</div>
  	</div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

  	<% flash.each do |name, msg| %>
  			<%= content_tag :div, msg, class: [:alert, alert_for(name)]%>
  		<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">

	<%= simple_form_for @post, html: { class: "form-horizontal", multipart: true } do |f| %>
		<div class="form-group">
			<%= f.input :image %>
		</div>
		<div class="form-group text-center">
			<%= f.input :caption %>
		</div>
		<div class="form-group text-center">
			<%= f.button :submit, :class => "btn-success" %>
		</div>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="row posts-wrapper">
		<div class="post">
			<div class="post-head">
				<div class="thumb-img">
				</div>
				<div class="user-name">
					<%= post.user.user_name %>
				</div>
				<div class="time-ago">
					<%= time_ago_in_words post.created_at %>
				</div>
			</div>
			<div class="image center-block">
				<%= link_to (cl_image_tag "post_#{post.id}_image", :width => 640, :height => 640, :class => "img-responsive" ), post_path(post) %>
			</div>
			<div class="post-bottom">
				<div class="caption">
					<div class="caption-content">
						<div class="user-name">
							<%= post.user.user_name %>
						</div>	
						<%= post.caption %>
					</div>
					<% if post.comments then %>
						<div class="comments" id=<%= "comments_#{post.id}" %>>
							<% post.comments.each do |comment| %>
								<%= render post.comments, post: post %>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
			<div class="comment-like-form row">
				<div class="like-button col-sm-1">
					<span class="glyphicon glyphicon-heart-empty"></span>
				</div>
				<div class="comment-form col-sm-11">
					<%= form_for([post, post.comments.new], remote: true) do |f| %>
						<%= f.text_field :content, :placeholder => 'Add a comment ...', class: "comment_content", id: "comment_content_#{post.id}"%>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="row posts-wrapper">
	<div class="image center-block">
		<%= image_tag @post.image.url(:medium), :class => "img-responsive" %>
	</div>
</div>
<%= render 'form' %>
<div class="text-center edit-links">
		<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %> | <%= link_to "Cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="text-center edit-links">
	<% if current_user.id == @post.user.id then %>
		<%= link_to "Cancel", posts_path %> | <%= link_to "Edit Post", edit_post_path(@post) %>
	<% else %>
		<%= link_to "Cancel", posts_path %>
	<% end %>
</div>